version: 2
updates:
  - package-ecosystem: npm
    directory: /client
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      dev-deps:
        dependency-type: development
      prod-deps:
        dependency-type: production
    labels:
      - dependencies
      - client

  - package-ecosystem: npm
    directory: /server
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      dev-deps:
        dependency-type: development
      prod-deps:
        dependency-type: production
    labels:
      - dependencies
      - server

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - ci
