import React, { useEffect, useState } from "react";
import { api } from "../api.js";

const STOPWORDS = new Set([
  "fresh", "frozen", "dried", "raw", "cooked", "whole", "chopped", "sliced",
  "diced", "minced", "grated", "shredded", "crushed", "peeled", "cleaned",
  "washed", "fine", "finely", "coarse", "coarsely", "thinly", "small", "medium",
  "large", "ground", "powdered", "optional", "or", "and", "to", "taste", "of",
]);

function contentTokens(s) {
  return String(s || "")
    .toLowerCase()
    .replace(/\([^)]*\)/g, "")
    .replace(/[^a-z0-9 ]+/g, " ")
    .split(/\s+/)
    .filter((t) => t && !STOPWORDS.has(t) && !/^\d+$/.test(t));
}

function isCovered(ingredientName, pantryNames) {
  const ing = contentTokens(ingredientName);
  if (!ing.length) return false;
  return pantryNames.some((p) => {
    const pt = contentTokens(p);
    if (pt.length !== ing.length) return false;
    const set = new Set(pt);
    return ing.every((t) => set.has(t));
  });
}

export default function RecipeDetail({ recipe, source, pantry = [], onClose, onShoppingChanged }) {
  const { id, name, region, tags = [], servings, prep_time_mins, cook_time_mins,
          ingredients = [], steps = [], notes } = recipe;
  const time = (prep_time_mins || 0) + (cook_time_mins || 0);

  const [status, setStatus] = useState(null);
  const [busy, setBusy] = useState(false);

  useEffect(() => { setStatus(null); }, [id]);

  const pantryNames = pantry.map((p) => p.name);
  const enriched = ingredients.map((i) => ({ ...i, have: isCovered(i.name, pantryNames) }));
  const missingCount = enriched.filter((x) => !x.have).length;

  async function addMissing() {
    if (!id) return;
    setBusy(true);
    setStatus(null);
    try {
      const data = await api.shopping.fromRecipe(id);
      const added = data.added?.length || 0;
      const skipped = data.skipped?.length || 0;
      setStatus({
        kind: "ok",
        text: added
          ? `Added ${added} item${added === 1 ? "" : "s"} to your shopping list${skipped ? ` (${skipped} already covered)` : ""}.`
          : "You're already covered — nothing to add.",
      });
      onShoppingChanged?.(data);
    } catch (err) {
      setStatus({ kind: "err", text: err.message });
    } finally {
      setBusy(false);
    }
  }

  return (
    <article className="detail">
      <div className="detail__head">
        <div style={{ flex: 1, minWidth: 0 }}>
          <h2 className="detail__title">{name}</h2>
          <div className="detail__meta">
            {region && <span>{region}</span>}
            {region && servings && <span>·</span>}
            {servings && <span>{servings} servings</span>}
            {time > 0 && <span>·</span>}
            {time > 0 && <span>{time} min total</span>}
            {tags.length > 0 && tags.slice(0, 4).map((t) => (
              <span key={t} className="chip">{t}</span>
            ))}
          </div>
          {source && (
            <div className="detail__source">
              {source === "ai" ? "✨ Freshly generated by AI" : "📚 From the recipe library"}
            </div>
          )}
        </div>
        <button type="button" className="detail__close" onClick={onClose} aria-label="Close recipe">
          ✕
        </button>
      </div>

      <div className="detail__cols">
        <div>
          <div className="detail__h">
            Ingredients
            <span className="detail__h-count">
              {ingredients.length - missingCount} of {ingredients.length} in pantry
            </span>
          </div>
          <ul className="ing-list">
            {enriched.map((i, idx) => (
              <li key={idx} className={i.have ? "is-have" : ""}>
                <span className={`ing-list__mark ${i.have ? "ing-list__mark--have" : "ing-list__mark--need"}`}>
                  {i.have ? "✓" : "·"}
                </span>
                <span className="ing-list__qty">
                  {i.quantity !== undefined && i.quantity !== null ? `${i.quantity} ` : ""}
                  {i.unit || ""}
                </span>
                <span className="ing-list__name">{i.name}</span>
              </li>
            ))}
          </ul>
        </div>

        <div>
          <div className="detail__h">
            Method
            <span className="detail__h-count">{steps.length} steps</span>
          </div>
          <ol className="step-list">
            {steps.map((s, idx) => <li key={idx}>{s}</li>)}
          </ol>
          {notes && <div className="detail__notes">{notes}</div>}
        </div>
      </div>

      <div className="detail__cta">
        <button type="button" className="btn btn--brand" onClick={addMissing} disabled={busy || missingCount === 0}>
          {busy ? "Adding…" : missingCount === 0
            ? "🛒 Nothing to buy"
            : `🛒 Add ${missingCount} missing item${missingCount === 1 ? "" : "s"} to shopping list`}
        </button>
        {status && (
          <span className={`detail__cta-msg ${status.kind === "ok" ? "is-ok" : "is-err"}`}>
            {status.text}
          </span>
        )}
      </div>
    </article>
  );
}
